### ISSUE TITLE
MqlInterpreter doesn't support order by clause

### ISSUE THREAD

**Issue by catchsrinik** [mulesoft-labs/mql#4]
MqlInterpreter  -  doesn't have support for order by clause in query.  

I tried with "orderby" and "order by" , same  exception.
Please correct me if the usage is wrong.

Query.execute("from users where companyId='1' and income>4000 order by income", context);

Exception in thread "main" com.mulesoft.mql.QueryException: com.mulesoft.mql.grammar.parser.ParserException: [1,48] expecting: EOF
    at com.mulesoft.mql.Query.create(Query.java:101)
    at com.mulesoft.mql.Query.execute(Query.java:120)

**Comment by catchsrinik** [comment]
Also "LIMIT" clause is missing , to limit the number of rows to return.
